GO
CREATE DATABASE SANDAUGIATRUCTUYEN

GO
USE SANDAUGIATRUCTUYEN

GO
CREATE TABLE NGUOIDUNG(
	ID INT NOT NULL IDENTITY,
	TenTaiKhoan VARCHAR NOT NULL,
	MatKhau VARCHAR NOT NULL,
	HoTen VARCHAR NOT NULL,
	NgaySinh DATE NOT NULL,
	Email VARCHAR NOT NULL,
	DiaChi VARCHAR,
	Loai INT NOT NULL,
	AvatarURL VARCHAR NOT NULL,
	TongDiemDanhGia INT NOT NULL
	PRIMARY KEY(ID)
)

CREATE TABLE SANPHAM(
	ID INT NOT NULL IDENTITY,
	TenSanPham VARCHAR NOT NULL,
	Gia FLOAT NOT NULL,
	ThoiGianConLai TIME NOT NULL,
	SoLanDuocDauGia INT,
	IDLoai INT NOT NULL,
	IDNguoiBan INT NOT NULL,
	IDNguoiThangDauGia INT,
	PRIMARY KEY(ID)
)

CREATE TABLE LOAI(
	ID INT NOT NULL IDENTITY,
	TenLoai VARCHAR NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE HINHANH(
	IDSanPham INT NOT NULL,
	IDHinh INT NOT NULL,
	ImgURL VARCHAR,
	PRIMARY KEY(IDSanPham, IDHinh)
)

CREATE TABLE CHITIETDAUGIA(
	IDNguoiDauGia INT NOT NULL,
	IDSanPham INT NOT NULL,
	ThoiGianDauGia DATETIME NOT NULL,
	Gia FLOAT,
	PRIMARY KEY(IDNguoiDauGia, IDSanPham, ThoiGianDauGia)
)

CREATE TABLE CHITIETDANHGIA(
	IDNguoiDuocDanhGia INT NOT NULL,
	IDNguoiDanhGia INT NOT NULL,
	ThoiGianDanhGia DATETIME NOT NULL,
	DiemDanhGia INT NOT NULL,
	NhanXet VARCHAR,
	PRIMARY KEY(IDNguoiDuocDanhGia, IDNguoiDanhGia, ThoiGianDanhGia)
)

CREATE TABLE SANPHAMYEUTHICH(
	IDSanPham INT NOT NULL,
	IDNguoiDung INT NOT NULL,
	PRIMARY KEY(IDSanPham, IDNguoiDung)
)

CREATE TABLE THAMSO(
	ID INT NOT NULL IDENTITY,
	ChiPhiDangSanPham FLOAT,
	PRIMARY KEY(ID)
)

ALTER TABLE SANPHAM ADD CONSTRAINT FK_SANPHAM_NGUOIDUNGBAN FOREIGN KEY(IDNguoiBan) REFERENCES NGUOIDUNG(ID)
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SANPHAM_LOAI FOREIGN KEY(IDLoai) REFERENCES LOAI(ID)
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SANPHAM_NGUOIDUNGTHANG FOREIGN KEY(IDNguoiThangDauGia) REFERENCES NGUOIDUNG(ID)
ALTER TABLE HINHANH ADD CONSTRAINT FK_HINHANH_SANPHAM FOREIGN KEY(IDSanPham) REFERENCES SANPHAM(ID)
ALTER TABLE CHITIETDAUGIA ADD CONSTRAINT FK_CHITIETDAUGIA_NGUOIDUNGDAUGIA FOREIGN KEY(IDNguoiDauGia) REFERENCES NGUOIDUNG(ID)
ALTER TABLE CHITIETDAUGIA ADD CONSTRAINT FK_CHITIETDAUGIA_SANPHAM FOREIGN KEY(IDSanPham) REFERENCES SANPHAM(ID)
ALTER TABLE CHITIETDANHGIA ADD CONSTRAINT FK_CHITIETDANHGIA_NGUOIDUNGDUOCDANHGIA FOREIGN KEY(IDNguoiDuocDanhGia) REFERENCES NGUOIDUNG(ID)
ALTER TABLE CHITIETDANHGIA ADD CONSTRAINT FK_CHITIETDANHGIA_NGUOIDUNGDANHGIA FOREIGN KEY(IDNguoiDanhGia) REFERENCES NGUOIDUNG(ID)
ALTER TABLE SANPHAMYEUTHICH ADD CONSTRAINT FK_SANPHAMYEUTHICH_NGUOIDUNG FOREIGN KEY(IDNguoiDung) REFERENCES NGUOIDUNG(ID)
ALTER TABLE SANPHAMYEUTHICH ADD CONSTRAINT FK_SANPHAMYEUTHICH_SANPHAM FOREIGN KEY(IDSanPham) REFERENCES SANPHAM(ID)
